network:
  version: 2
  renderer: networkd

  ethernets:
    eth0:
      dhcp4: false
      dhcp6: false

  bridges:
    cloudbr0:
      addresses: [172.31.100.2/16]
      dhcp4: false
      dhcp6: false
      interfaces:
      - eth0
      routes:
      - to: "default"
        via: "172.31.0.1"
      nameservers:
          addresses: [161.24.23.180]
      parameters:
        stp: false
        forward-delay: 0
