network:
  version: 2
  renderer: networkd

  ethernets:
    enp2s0:
      dhcp4: false
      dhcp6: false

  vlans:
    vlan16:
      id: 16
      link: enp2s0
      dhcp4: false
      dhcp6: false

  bridges:
    xenbr0:
      addresses:
      - "161.24.2.234/24"
      - "172.31.0.1/16"
      nameservers:
        addresses:
        - 161.24.23.180
        - 161.24.23.199
      dhcp4: false
      dhcp6: false
      interfaces:
      - vlan16
      routes:
      - to: "default"
        via: "161.24.2.1"
        metric: 100
      - to: "161.24.2.0/24"
        via: "161.24.2.1"
        metric: 100
        table: 100
      - to: "default"
        via: "172.31.0.1"
        metric: 200
      - to: "172.31.0.0/16"
        via: "172.31.0.1"
        metric: 200
        table: 200
      routing-policy:
      - from: "161.24.2.0/24"
        table: 100
      - from: "172.31.0.0/16"
        table: 200
      parameters:
        stp: false
        forward-delay: 4
