network:
  version: 2
  renderer: networkd

  ethernets:
    enp2s0f0:
      dhcp4: false
      dhcp6: false
    enp2s0f1:
      addresses:
      - "172.31.0.1/16"
      dhcp4: false
      dhcp6: false

  bridges:
    xenbr0:
      addresses:
      - "161.24.23.103/24"
      dhcp4: false
      dhcp6: false
      interfaces:
      - enp2s0f0
      routes:
        - to: default
          via: 161.24.23.1
          metric: 100
        - to: 161.24.23.0/24
          via: 161.24.23.1
          metric: 100
          table: 100
      routing-policy:
        - from: 161.24.23.0/24
          table: 100
