network:
  version: 2
  renderer: networkd
  ethernets:
    enp2s0f0:
      dhcp4: false
      dhcp6: false

    enp2s0f1:
      dhcp4: 10.0.0.1
      dhcp6: false
      nameservers:
        addresses:
        - 161.24.23.180
        - 161.24.23.199

  bridges:
    xenbr0:
      interfaces:
      - enp2s0f0
      addresses:
      - 161.24.23.103/24
      - 10.0.0.2/8
      routes:
        - to: default
          via: 161.24.23.1
          metric: 100
        - to: 161.24.23.0/24
          via: 161.24.23.1
          metric: 100
          table: 100
        - to: default
          via: 10.0.0.1
          metric: 200
        - to: 10.0.0.0/8
          via: 10.0.0.1
          metric: 200
          table: 200
      routing-policy:
        - from: 161.24.23.0/24
          table: 100
        - from: 10.0.0.0/8
          table: 200
      dhcp4: false
      dhcp6: false
      nameservers:
        addresses:
        - 161.24.23.180
        - 161.24.23.199
      parameters:
        stp: true 
        forward-delay: 4
