#!/usr/bin/env bash
set -euo pipefail

MARIADB_HOST=172.1.19.200
MARIADB_PWD=9470eb6e164da764

ADMIN_PASS=s3cr37
CONTROLLER=localhost

DEBIAN_FRONTEND=noninteractive

# Tunel para DB
# Configurar auto-login:
#    cat .ssh/id_ed25519.pub | ssh -p 2222 gpes@dev.labqs.ita.br 'cat >> .ssh/authorized_keys'
ssh -p 2222 -fN -L 3306:$MARIADB_HOST:3306 gpes@dev.labqs.ita.br

sed -i 's/@MARIADB_PWD/'${MARIADB_PWD}'/g' ./config/keystone/keystone.conf

apt-get update -y && apt-get upgrade -y && \
apt-get install -y keystone && \
/bin/sh -c "keystone-manage db_sync" keystone && \
keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone && \
keystone-manage credential_setup --keystone-user keystone --keystone-group keystone && \
keystone-manage bootstrap --bootstrap-password ${ADMIN_PASS} \
    --bootstrap-admin-url https://${CONTROLLER}/keystone/v3 \
    --bootstrap-internal-url https://${CONTROLLER}/keystone/v3 \
    --bootstrap-public-url https://${CONTROLLER}/keystone/v3 \
    --bootstrap-region-id RegionOne

export OS_USERNAME=admin
export OS_PASSWORD=${ADMIN_PASS}
export OS_PROJECT_NAME=admin
export OS_USER_DOMAIN_NAME=Default
export OS_PROJECT_DOMAIN_NAME=Default
export OS_AUTH_URL=https://${CONTROLLER}/keystone/v3
export OS_IDENTITY_API_VERSION=3
