services:

  cloudstack:
    container_name: cloudstack
    build:
      context: .
      dockerfile: Dockerfile
    image: labqs/cloudstack:latest
    restart: unless-stopped
    ports:
      - '8080:8080'
      - '8443:8443'
      - '8250:8250'
      - '9090:9090'
    networks:
      netlab01:
        ipv4_address: '172.16.1.200'

networks:
  netlab01:
    external: true
